# Uygulama Ad\u0131 (Eureka'da bu isimle g\u00f6r\u00fcnecek)
spring.application.name=api-gateway

# Gateway Portu (Ana giri\u015f kap\u0131m\u0131z buras\u0131 olacak)
server.port=8080

# Eureka Server Adresi (Rehbere kay\u0131t olmak i\u00e7in)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Rotalar\u0131 Eureka'dan otomatik \u00f6\u011fren (User service nerede, Car service nerede diye sormas\u0131 i\u00e7in)
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true