# Servisin Adı
spring.application.name=car-service

# Çalışacağı Port (8080 dolu, 8081 yapıyoruz)
server.port=8081

# Veritabanı Bağlantısı (Bilgisayarında MongoDB kurulu olduğunu varsayıyoruz)
spring.data.mongodb.uri=mongodb://localhost:27017/car-db

# Eureka'ya Kayıt Olma
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/