spring.application.name=user-service

# Port Ayarı (Gateway 8080 idi, bu 8082 olsun)
server.port=8082

# Eureka Bağlantısı
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# PostgreSQL Bağlantı Ayarları
# (Furkan kendi bilgisayarındaki şifreyi 'password' kısmına yazmalı!)
spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Ayarları (Tabloları otomatik oluşturur)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Actuator Configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always