# Sunucunun \u00e7al\u0131\u015faca\u011f\u0131 port (Varsay\u0131lan 8761'dir)
server.port=8761

# Uygulama Ad\u0131
spring.application.name=discovery-server

# Bu bir sunucu oldu\u011fu i\u00e7in kendisini 'register' etmemeli
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Loglar\u0131 takip etmek i\u00e7in (Opsiyonel)
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF